CREATE TABLE `paynow_txn_data` (
	`ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`RETRIEVAL_REF` varchar(20) NOT NULL,
	`INSTITUTION_CODE` varchar(20) NOT NULL,
	`TID` varchar(20) NOT NULL,
	`TRANSACTION_ID` int(12) DEFAULT NULL,
	`CREDIT_AMOUNT` decimal(20,4) NOT NULL,
	`CREDIT_CURRENCY` varchar(5) NOT NULL,
	`CREDITING_TIME` varchar(15) NOT NULL,
	`RECEIVING_ACCOUNT_NUMBER` varchar(50) NOT NULL,
	`RECEIVING_ACCOUNT_TYPE` varchar(5) NOT NULL,
	`MERCHANT_REFERENCE_NUMBER` varchar(50) NOT NULL,
	`SENDING_ACCOUNT_BANK` varchar(50) DEFAULT NULL,
	`SENDING_ACCOUNT_NUMBER` varchar(50) DEFAULT NULL,
	`SENDING_ACCOUNT_NAME` varchar(100) DEFAULT NULL,
	`ADDITIONAL_BANK_REFERENCE` varchar(50) DEFAULT NULL,
	`REVERSAL_REFUND_REFERENCE` varchar(255) DEFAULT NULL,
	`CREATION_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	 PRIMARY KEY (`ID`),
	 KEY `PAYNOW_TXN_DATA_RETRIEVAL_REF` (`RETRIEVAL_REF`),
	 KEY  `PAYNOW_TXN_DATA_TRANSACTION_ID` (`TRANSACTION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO nps_sequence (name, increment, min_value, max_value, cur_value,cycle ) VALUES ('paynow_dynamic_stan', 1,000001,999999,1,true);
INSERT INTO nps_sequence (name, increment, min_value, max_value, cur_value,cycle ) VALUES ('paynow_dynamic_seqnum', 1,00000001,99999999,1,true);
ALTER TABLE ttr30_aps_request MODIFY  RETRIEVAL_REF_NO VARCHAR(20);
ALTER TABLE `ta02_acq_mer_account` ADD KEY  `POSID_ACQID_CURRENCY_IDX`(`POS_ID`, `ACQUIRER_ID`, `SOURCE_CURRENCY`);
ALTER TABLE `tm15_merchant_cfg_attr` ADD KEY  `MER_ID_CFG_ATTR_NAME_IDX`(`MERCHANT_ID`, `cfgAttrName`);
ALTER TABLE `error_event` MODIFY `ERROR_MESSAGE` VARCHAR(200);
